### ISSUE TITLE
Copy URL not working

### ISSUE THREAD

**Issue by klakar** [style-hub/hub-server#1]
When you press the "Copy" button to copy the style url, this will not work!
Unless you are running the server on _localhost_ or with __https__.
This is not a bug, as far as I know, but something to be aware of.

Workaround:
You can still right-click the XML button and copy the link that way.

**Comment by sigmoe** [comment]
It's a very interesting website, but why isn't it in https to allow the 'copy' button ?
The right-click (and copy) on the XML button doesn't work: when I paste it in QGIS, I've got a message indicating that it's not a good file (it seems to be a problem of javascript).

**Comment by klakar** [comment]
Style hub is now implemented on plugins.qgis.org.
