### ISSUE TITLE
New Hub about symbologies

### ISSUE THREAD

**Issue by ambarja** [style-hub/hub-server#6]
Hi Karls my name is Antony in this opportunity I want to share a simple project that I've been developing similar to Style-Hub.This project is about free symbologies for QGIS in SVG and PNG format, all this in one page where you can download for free. Maybe this project can be improved later to join a future Home Page Hub.
What do you think about this ? Is a good idea or not? 
:) 
Regards!

![Captura de pantalla de 2020-10-13 22-47-39](https://user-images.githubusercontent.com/23284899/95941397-506d3a80-0da6-11eb-8cf1-4ab78bb0473d.png)

GitHub Project :point_down: 
* https://github.com/qgispe/Symbology-Hub

**Comment by klakar** [comment]
This could be a nice addition to the hub concept. However this type of resources need to be packaged in an archive in order for it to be simple to use, and QGIS will not do that for you. And the archive will need to be unpacked when downloaded. From a ease of use perspective it would probably be easier to use the resource sharing plugin for things like SVG's and graphics.
If we could get an "import/export" function for this kind of resources in QGIS, then it will be more feasible.
There are some plans to re-design the QGIS.org plug-in website and maybe include a style-hub. If so, we should see in what way that will be designed and work towards including official additions there.

**Comment by klakar** [comment]
I'm closing this issue for now.
